[package]
name = "excel2csv"
version = "0.1.0"
edition = "2021"
author = "Mike Mannakee"
about = "Converts Excel files to CSV files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.22.1"
